name: Basic job

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}