name: Changed Files
on:
  push:
    paths:
      - changed-files/**
      - .github/workflows/changed-files.yml

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "commits=${{ github.event.commits }}" >> $GITHUB_OUTPUT
          echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.commits[0][sha] }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
          echo "ts=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.commits[0][sha] }} ${{ github.sha }} | grep .ts$ | xargs)" >> $GITHUB_OUTPUT
    # Map a step output to a job output
    outputs:
      commits: ${{ steps.changes.outputs.commits}}
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}

  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    # if: ${{needs.changedfiles.outputs.ts}}
    steps:
      - name: echo changed files
        run: |
          echo ${{needs.changedfiles.outputs.commits}}
          echo ${{needs.changedfiles.outputs.ts}}
          echo ${{needs.changedfiles.outputs.all}}