name: Compile cosmwasm source code

on:
  workflow_dispatch

jobs:
  compile-cosmwasm:
    name: Compile cosmwasm contract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: ./compile/
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        
      - name: cargo build
        working-directory: ./compile/source-code/cosmwasm/abi-storage
        run: |
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown
          mkdir -p ../../../wasm
          cp ./target/wasm32-unknown-unknown/release/abi_storage.wasm ../../../wasm
          git add ../../../wasm
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git commit -m "action: .wasm save test"
          git push
        
      # todo:
      # 아예 job 단계부터 분리해야 될것 같다.
      # github actions 변수 사용 방법 다시 알아보기
      #
      # - name: commit & push
      #   working-directory: ./compile/source-code/cosmwasm/abi-storage
      #   run: |
      #     git add .
      #     git commit -m "action: .wasm save test"
      #     git push  
      # 이후 commit으로 compile 결과 고정