name: Compile cosmwasm source code

on:
  workflow_dispatch

jobs:
  compile-cosmwasm:
    name: Compile cosmwasm contract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: ./compile/
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        
      - name: cargo build
        working-directory: ./compile/source-code/cosmwasm/abi-storage
        run: |
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown
          mkdir -p ../../../wasm && cp target/wasm32-unknown-unknown/release/abi-storage.wasm ../../../wasm
          cd ../../../wasm
          git add abi-storage.wasm
          git commit -m "action: .wasm save test"
          git push
          
          
      # 이후 commit으로 compile 결과 고정