name: Compile cosmwasm source code

on:
  workflow_dispatch

jobs:
  compile-cosmwasm:
    name: Compile cosmwasm contract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./compile/