name: Pull request label test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  diff-check-job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    # outputs:
    #   output1: ${{ steps.step1.outputs.path }}

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          SET_ENV_NAME_COUNT: diff_count
          PATTERNS: |
            pr-test/test1/**/
      - name: print git diff
        id: step1
        run: echo "${{ env.GIT_DIFF }}"
      - name: print git diff filtered
        id: step2
        run: echo "${{ env.GIT_DIFF_FILTERED }}"
      - name: print git diff count
        id: step3
        run: echo "${{ env.diff_count }}"

  # 다른 job에서 전체 결과에 대한 output을 어디에 저장해 놓고 사용하는 방법..

  # job2:
  #   runs-on: ubuntu-latest
  #   needs: diff-check-job
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.diff-check-job.outputs.output1}}
  #       run: echo "$OUTPUT1"
