name: Pull request label test

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  diff-check-job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    # outputs:
    #   output1: ${{ steps.step1.outputs.path }}
    steps:
      - uses: technote-space/get-diff-action@v6
        with:
          SET_ENV_NAME_COUNT:
          PATTERNS: |
            pr-test/test1/**
      - name: print git diff
        id: step1
        run: echo "${{ env.GIT_DIFF }}"
      - name: print git diff filtered
        id: step2
        run: echo "${{ env.GIT_DIFF_FILTERED }}"
      - name: print git diff count
        id: step3
        run: echo "${{ env.count }}""
  
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: diff-check-job
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.diff-check-job.outputs.output1}}
  #       run: echo "$OUTPUT1"




        # diff, filtered가 같은지 확인 -> 특정 디렉토리 이외의 변경이 있는지 확인 가능