name: Pull request label test

on:
  workflow_dispatch:

jobs:
  diff-check-job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.path }}
    steps:
      - name: get diff path
        id: step1
        run: echo "path=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
      - name: log diff path
        id: step2
        run: echo "${{ steps.step1.outputs.path.length }}"
      - name: check diff path
        id: step3
        run: exit 1
        if: ${{ steps.step1.outputs.path.length != 1 }}
  
  job2:
    runs-on: ubuntu-latest
    needs: diff-check-job
    steps:
      - env:
          OUTPUT1: ${{needs.diff-check-job.outputs.output1}}
        run: echo "$OUTPUT1"