name: Pull request label test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  diff-check-job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    # outputs:
    #   output1: ${{ steps.step1.outputs.path }}

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          SET_ENV_NAME_COUNT: diff_count
          PATTERNS: |
            pr-test/test1/**
      - name: print git diff
        id: step1
        run: echo "${{ env.GIT_DIFF }}"
      - name: print git diff filtered
        id: step2
        run: echo "${{ env.GIT_DIFF_FILTERED }}"
      - name: print git diff count
        id: step3
        run: echo "${{ env.diff_count }}"
      - name: print custom git diff
        id: step4
        run: |
          diff="${{env.GIT_DIFF}}"

          p1=${$diff[0] | cut -d '/' -f1}
          p2=${$diff[0] | cut -d '/' -f1}
          p3=${$diff[0] | cut -d '/' -f1}

          path="$p1/$p2/$p3/"
          echo $path
          for i in $diff
          do
            if [[ $i == $path* ]]; then
              echo $i
            fi
            if [[ $i != $path* ]]; then
              exit 1
            fi
          done

  # diff="${{env.GIT_DIFF}}"
  # path="${diff[0]:0:14}}" <- project diectory 이름까지 가져올 수 있는 방법
  # echo $path
  # for i in "${{ env.GIT_DIFF }}"
  # do
  #   if [[ $i == $path* ]]; then
  #     echo $i
  #   fi
  #   if [[ $i != $path* ]]; then
  #     exit 1
  #   fi
  # done       

  # project_path 변수 하나 선언해 놓고

  # job2:
  #   runs-on: ubuntu-latest
  #   needs: diff-check-job
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.diff-check-job.outputs.output1}}
  #       run: echo "$OUTPUT1"
