name: Pull request label test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  diff-check-job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      project_path: ${{ steps.step4.outputs.project_path }}
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          SET_ENV_NAME_COUNT: diff_count
          PATTERNS: |
            pr-test/test1/**
      - name: print git diff
        id: step1
        run: echo "${{ env.GIT_DIFF }}"
      - name: print git diff filtered
        id: step2
        run: echo "${{ env.GIT_DIFF_FILTERED }}"
      - name: print git diff count
        id: step3
        run: echo "${{ env.diff_count }}"
      - name: check number of project
        id: step4
        run: |
          diff="${{ env.GIT_DIFF }}"
          IFS=' ' read -r -a diff_files <<< "$diff"
          tail="${diff_files[0]#*/*/*/}"
          head="${diff_files[0]%$tail}"
          project_path="${head:1}"
          echo $project_path
          for i in ${{ env.GIT_DIFF }}
          do
            echo $i
            if [[ $i != $project_path* ]]
            then
              exit 1
            fi
          done
          echo "project_path=$project_path" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: diff-check-job
    steps:
      - env:
          PROJECT_PATH: ${{needs.diff-check-job.outputs.project_path}}
        run: echo "$PROJECT_PATH"
