name: Say Hello

on:
 push:
   paths:
    - scripts/helloworld.js

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
